"""add portal fields to solicitacao

Revision ID: 013857051b78
Revises: 9a0c42b24f4b
Create Date: 2026-03-09 23:22:48.492459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '013857051b78'
down_revision: Union[str, None] = '9a0c42b24f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacao', sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('solicitacao', sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_solicitacao_portal_id'), 'solicitacao', ['portal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacao_portal_id'), table_name='solicitacao')
    op.drop_column('solicitacao', 'portal_name')
    op.drop_column('solicitacao', 'portal_id')
    # ### end Alembic commands ###
