"""add evento table

Revision ID: 4ec26f37fdb7
Revises: ff47bdcebf3e
Create Date: 2026-03-07 00:48:00.549239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ec26f37fdb7'
down_revision: Union[str, None] = 'ff47bdcebf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destinatario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_destinatario'), 'evento', ['destinatario'], unique=False)
    op.create_index(op.f('ix_evento_portal_id'), 'evento', ['portal_id'], unique=False)
    op.create_index(op.f('ix_evento_status'), 'evento', ['status'], unique=False)
    op.create_index(op.f('ix_evento_tipo'), 'evento', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evento_tipo'), table_name='evento')
    op.drop_index(op.f('ix_evento_status'), table_name='evento')
    op.drop_index(op.f('ix_evento_portal_id'), table_name='evento')
    op.drop_index(op.f('ix_evento_destinatario'), table_name='evento')
    op.drop_table('evento')
    # ### end Alembic commands ###
