"""add solicitacao table

Revision ID: 9a0c42b24f4b
Revises: 183871aa523c
Create Date: 2026-03-09 23:17:06.325470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a0c42b24f4b'
down_revision: Union[str, None] = '183871aa523c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prioridade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orgao_responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao_resumida', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pessoas_afetadas', sa.Integer(), nullable=False),
    sa.Column('animais_afetados', sa.Integer(), nullable=False),
    sa.Column('risco_imediato', sa.Boolean(), nullable=False),
    sa.Column('protocolo_atendimento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endereco_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_solicitacao_orgao_responsavel'), 'solicitacao', ['orgao_responsavel'], unique=False)
    op.create_index(op.f('ix_solicitacao_prioridade'), 'solicitacao', ['prioridade'], unique=False)
    op.create_index(op.f('ix_solicitacao_risco_imediato'), 'solicitacao', ['risco_imediato'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacao_risco_imediato'), table_name='solicitacao')
    op.drop_index(op.f('ix_solicitacao_prioridade'), table_name='solicitacao')
    op.drop_index(op.f('ix_solicitacao_orgao_responsavel'), table_name='solicitacao')
    op.drop_table('solicitacao')
    # ### end Alembic commands ###
