"""add_kpi_table

Revision ID: ac05b85c4e38
Revises: a1b2c3d4e5f6
Create Date: 2026-03-06 20:31:38.366024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac05b85c4e38'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpihistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_kpi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpihistory')
    # ### end Alembic commands ###
