"""empty message

Revision ID: f824054c5b79
Revises: a1b2c3d4e5f6
Create Date: 2026-03-06 23:57:10.872630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f824054c5b79'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pedido', sa.Column('origem', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pedido', sa.Column('categoria_item', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pedido', sa.Column('quantidade', sa.Integer(), nullable=True))
    op.add_column('pedido', sa.Column('unidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pedido', sa.Column('urgencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pedido', sa.Column('ponto_destino', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'ponto_destino')
    op.drop_column('pedido', 'urgencia')
    op.drop_column('pedido', 'unidade')
    op.drop_column('pedido', 'quantidade')
    op.drop_column('pedido', 'categoria_item')
    op.drop_column('pedido', 'origem')
    op.drop_column('pedido', 'data_criacao')
    # ### end Alembic commands ###
