"""add slug to api_key

Revision ID: ff47bdcebf3e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-07 00:32:56.132478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff47bdcebf3e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('api_key', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.execute("UPDATE api_key SET slug = LOWER(REPLACE(TRIM(name), ' ', '-'))")
    op.alter_column('api_key', 'slug', nullable=False)
    op.create_index(op.f('ix_api_key_slug'), 'api_key', ['slug'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_slug'), table_name='api_key')
    op.drop_column('api_key', 'slug')
    # ### end Alembic commands ###
